FROM scratch

COPY cross-build/resin-xbuild /usr/bin/resin-xbuild
COPY cross-build/resin-xbuild /usr/bin/cross-build-start
COPY cross-build/resin-xbuild /usr/bin/cross-build-end
COPY cross-build/qemu-arm-static /usr/bin/qemu-arm-static
