sudo: required
services: docker
language: bash

git:
  depth: 1

env:
  global:
    - REPO=elfabio972/crossbuilder

before_script:
    - uname -a
    - curl -LO https://storage.googleapis.com/container-structure-test/v0.2.1/container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/
#    - docker --version
#    - which docker-compose
#    - env
#    - sudo apt-get update
#    - sudo apt-get install tree
#    - tree

script:
    - make build TARGET=armhf
    - make build TARGET=aarch64
    - make test TARGET=armhf
    - make test TARGET=aarch64
    - docker images
    - container-structure-test -test.v -image ${REPO}:armhf container-tests/tests-armhf.yaml
    - container-structure-test -test.v -image ${REPO}:aarch64 container-tests/tests-aarch64.yaml