sudo: required
services: docker
language: bash

git:
  depth: 1

stages:
    - test
    - demo
    - test-struct
    - deploy

env:
  global:
    - REPO=${DOCKER_USERNAME}/crossbuilder
  matrix:
    - ARCH=armhf
    - ARCH=aarch64

before_script:
    - uname -a
    - curl -LO https://storage.googleapis.com/container-structure-test/v0.2.1/container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/
#    - docker --version
#    - which docker-compose
#    - env
#    - sudo apt-get update
#    - sudo apt-get install tree
#    - tree

script:
    - make build TARGET=${ARCH}
    - echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
    - make push TARGET=${ARCH}
    - docker images
#    - make test TARGET=${ARCH}
#    - docker images
#    - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml

jobs:
    include:
        - .demo: &demo
            stage: test-struct
            script:
                - echo "${ARCH}"
                - docker pull ${REPO}:${ARCH}
                - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml
        - <<: *demo
          env:
            - ARCH=aarch64
        - stage: test-struct
          script:
            - docker images
            - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml
        - stage: deploy
          script:
            - docker images
            - echo "Deploying ${REPO}:${ARCH}"