sudo: required
services: docker
language: bash

git:
  depth: 1

stages:
    - build
    - test
    - deploy

env:
  global:
    - REPO=elfabio972/crossbuilder
  matrix:
    - ARCH=armhf
    - ARCH=aarch64

before_script:
    - uname -a
    - curl -LO https://storage.googleapis.com/container-structure-test/v0.2.1/container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/
#    - docker --version
#    - which docker-compose
#    - env
#    - sudo apt-get update
#    - sudo apt-get install tree
#    - tree

#script:
#    - make build TARGET=${ARCH}
#    - make test TARGET=${ARCH}
#    - docker images
#    - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml

jobs:
    include:
        - stage: build
          script:
            - docker images
            - make build TARGET=${ARCH}
            - docker images
        - stage: test
          script:
            - docker images
            - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml
        - stage: deploy
          script:
            - docker images
            - echo "Deploying ${REPO}:${ARCH}"