sudo: required
services: docker
language: bash

git:
  depth: 1

env:
  global:
    - REPO=elfabio972/crossbuilder

before_script:
    - uname -a
#    - docker --version
#    - which docker-compose
#    - env
#    - sudo apt-get update
#    - sudo apt-get install tree
#    - tree

script:
    - make build TARGET=armhf
    - make build TARGET=aarch64
    - make samples TARGET=armhf
    - make samples TARGET=aarch64
    - docker images