sudo: required
services: docker
language: bash

git:
  depth: 1

stages:
    - test
    - test-images
    - tag

env:
  global:
    - REPO=${DOCKER_USERNAME}/crossbuilder
    - TRAVIS_QUALIFIER=-travis-ci
  matrix:
    - ARCH=armhf
    - ARCH=aarch64

before_script:
    - uname -a
    - curl -LO https://storage.googleapis.com/container-structure-test/v0.2.1/container-structure-test && chmod +x container-structure-test && sudo mv container-structure-test /usr/local/bin/
#    - docker --version
#    - which docker-compose
#    - env
#    - sudo apt-get update
#    - sudo apt-get install tree
#    - tree

script:
    - make build TAG=${ARCH} VARIANT=${TRAVIS_QUALIFIER}
    - echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
    - make push TAG=${ARCH} VARIANT=${TRAVIS_QUALIFIER}
    - docker images
#    - make test TARGET=${ARCH}
#    - docker images
#    - container-structure-test -test.v -image ${REPO}:${ARCH} container-tests/tests-${ARCH}.yaml

jobs:
    include:
        - &test_image
          stage: test-images
          env:
            - ARCH=armhf
          script:
            - echo "${ARCH}"
            - docker pull ${REPO}:${ARCH}${TRAVIS_QUALIFIER}
            - container-structure-test -test.v -image ${REPO}:${ARCH}${TRAVIS_QUALIFIER} container-tests/tests-${ARCH}.yaml
        - <<: *test_image
          env:
            - ARCH=aarch64
        - &tag_image
          stage: tag
          env:
            - ARCH=armhf
          script:
            - echo "Tagging ${REPO}:${ARCH}"
            - docker pull ${REPO}:${ARCH}${TRAVIS_QUALIFIER}
            - echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
            - docker tag ${REPO}:${ARCH}${TRAVIS_QUALIFIER} ${REPO}:${ARCH}
        - <<: *tag_image
          env:
            - ARCH=aarch64
